languageCode = "en-us"
title = "Giftcard Service Interface"
theme = "hugo-material-docs"
canonifyurls = true
metaDataFormat = "yaml"

#googleAnalytics = "UA-XXXXXXXX-X"

[params]
	# General information
	copyright = "Released under the Apache 2.0 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/electrumpayments/giftcard-service-interface"

	logo = "images/logo-square.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

  [params.palette]
    primary = "cyan"
    accent  = "orange"

  [params.font]
    text = "Ubuntu"
    code = "Ubuntu Mono"

[social]
	github  = "electrumpayments"

[[menu.main]]
  name = "Specification"
  weight = 90

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
